enyo.depends(
	"AutoComplete",
	"ConfirmDialog",
	"DatePicker",
	"DecimalInput",
	"Divider",
	"DividerDrawer",
	"GAPI",
	"InlineNotification",
	"Joystick",
	"Keyboard",
	"LazyList",
	"ProgressDialog",
	"PrototypeExt",
	"SelectedMenu",
	"SelectorBar",
	"TimePicker",
	"ToggleBar"
);
